### PR TITLE
Wpf and validating binding API

### PR DESCRIPTION
**Pull request by mattstermiller**
This is a big one...

- Extends the existing WinForms Binding API with "validating" binding functions that support binding to Result model properties and showing errors with ErrorProviders
- Improves the WinForms Show extensions to be easier to use, adds extension for Run, and adds C#-friendly versions of these extensions
- Adds full support for WPF with a binding API for WPF controls and VinylUI extensions of Run, Show, ShowDialog
- Adds a well-documented example WPF app much larger than the existing example app

### CODE REVIEW

**Comment by pcharbon70** [comment]
Great update! Been considering F# for a new project and the lack of proper desktop UI frameworks was the main reason I fell back to C# WPF. Totally new to F# but going to give this a try.  Love the well documented new ContactManager code.

**Comment by mattstermiller** [comment]
Great to hear! I hope the example app is clear enough for you to follow along. If you have any questions, please open an issue and I would be happy to assist. I am in the process of writing a guide to building apps with VinylUI, but it may take a few weeks since I have rather limited time to work on it.

Also, I will be releasing this update on NuGet as version 2.0, hopefully today.

**Comment by mattstermiller** [comment]
@pcharbon70 v2.0 is now available on NuGet: https://www.nuget.org/packages/VinylUI/

**Comment by pcharbon70** [comment]
Thank you! Built it earlier without a glitch too.

**Pull request merged**
